### ISSUE TITLE
MIA crash on 1.12.2

### ISSUE THREAD

**Issue by 23KiaraMinecraft** [SokyranTheDragon/Minor-Integrations-and-Additions-MIA-#35] opened 2022-05-01 00:44 UTC
So, I had just installed Minor Integrations and Additions (MIA) into my modpack and it crashed saying that it was an error from MIA.

I'm on 1.12.2 with the latest version of Forge.

Crash Report: https://paste.ee/p/yS1dN

Latest Log: https://paste.ee/p/I2ZDg

**Comment by Codetoil** [comment] 2022-05-01 23:54
Duplicate of #33.

**Comment by SokyranTheDragon** [comment] 2022-05-20 16:36
Should be fixed by ce8009e1b97f877c2cb9c332d2c3c598b25b7982, update should be released soon.

**Closed as completed by SokyranTheDragon** 2022-05-20 16:36 UTC
