### ISSUE TITLE
Crash with FutureMC (0.2.7.3) [NoClassDefFoundError: thedarkcolour.futuremc.item.FireproofArmorItem]

### ISSUE THREAD

**Issue by aking4125** [SokyranTheDragon/Minor-Integrations-and-Additions-MIA-#29] opened 2021-10-14 23:29 UTC
Hello,

Updated FutureMC to 0.2.7.3 and got the following crash from MIA:
[crash-2021-10-14_19.22.49-client.txt](https://github.com/SokyranTheDragon/Minor-Integrations-and-Additions-MIA-/files/7349860/crash-2021-10-14_19.22.49-client.txt)

Downgrading FutureMC or removing MIA fixes the crash and the game boots nornally. Any ideas?

**Comment by Codetoil** [comment] 2021-10-15 01:22
... I don't see `thedarkcolour.futuremc.item.FireproofArmorItem` referenced anywhere in the code... something has either gone horribly _horribly_ wrong, or MIA has been modified from its original state.

**Comment by aking4125** [comment] 2021-10-15 14:19
Modified from its original state? If you mean a JAR edit we have no idea how to even pull that off. I am just reporting what happened after we simply updated FutureMC. 

We deleted the MIA config folder then tried again with FutureMC 0.2.7.3 while also using a fresh jar file from curseforge. Still the same result. We tried deleting the config file for FutureMC. Still the same result.

We then tried it with just MIA and FutureMC 0.2.7.3 alone (Forglin as well) and it does boot normally. So there is in fact some type of other conflict somewhere. No idea what as of yet.

I downloaded the mod(s) again fresh from Curseforge and did a MD5 check in case. Both are the same.

![image](https://user-images.githubusercontent.com/11141831/137498619-bff6a9d6-8ffa-42a0-80df-cc6c0c3c0ba0.png)

![image](https://user-images.githubusercontent.com/11141831/137500518-030fbd29-5cd8-4545-b815-8a30af5bd5a1.png)

We're simply reporting what was found was all. We'll slowly check all the mod jars a few at a time to see where the conflict is.

**Comment by Codetoil** [comment] 2021-10-15 15:39
Perhaps it's a script, like a ZenScript file made for CraftTweaker-2. Based on the crash report, CraftTweaker-2 looks to be part of the modpack.

**Comment by aking4125** [comment] 2021-10-15 15:45
Hmmm. We'll take a look at that as well.

**Comment by thedarkcolour** [comment] 2021-10-31 15:53
I can't reproduce this

**Comment by aking4125** [comment] 2021-11-04 12:29
I'm still having trouble figuring out the conflicting mod or config as I haven't figured it out yet. Until I do, should we close this for now. Sorry, work has been eating up all my time. I can confirm it's not either FutureMC or MIA as together alone works. So there's just a conflict somewhere.

**Comment by Codetoil** [comment] 2021-11-07 14:36
@SokyranTheDragon *ping*

**Comment by SokyranTheDragon** [comment] 2021-11-07 23:26
Alright, so first of all, I changed my notification settings, and I should be getting informed about any new issues as soon as they appear.

Second, this might take a little bit of time as I changed my hardware recently, and I'm having issues getting my dev environment running. Forge 1.12 is no longer supported, so there tend to be issues with it. I'm trying to get it to run. Honestly, I'm not exactly sure how long it'll take.

I believe that disabling FutureMC integration in settings should make everything work properly (or specific integrations between FutureMC and other mods - the crash log file tells me it crashed on Thermal Expansion, but it can affect other mods).

**Comment by Codetoil** [comment] 2021-11-08 14:28
@SokyranTheDragon You should port MIA to FG3+. It should work better with the newer computer.

**Comment by Codetoil** [comment] 2021-11-08 14:30
@SokyranTheDragon Also, we already discussed this, it's not MIA or FutureMC. Something else, perhaps a script, is causing it to crash.
So you should close the issue I suppose.

**Comment by SokyranTheDragon** [comment] 2021-11-08 17:23
@Codetoil oh, I tried to port it to FG3+, including yesterday. It always ends up either crashing, or just not building and giving me a couple of errors I'm unable to fix (and looking on the internet doesn't help all that much).

And I feel like I should at least try to check on my end if it's this mod's issue or not. I feel like there's a genuine chance it's the case.

**Comment by Codetoil** [comment] 2021-11-08 17:32
@SokyranTheDragon Could you post them in a separate issue? Perhaps make an issue named "Port to FG3+"

**Comment by Codetoil** [comment] 2021-11-08 17:35
@SokyranTheDragon Maybe I could take a look.

**Comment by SokyranTheDragon** [comment] 2021-11-09 22:48
Alright, opened up the project (finally). Seems like some changes to FutureMC caused errors in the project, which is causing issues when it's paired with Thermal Expansion. Fix should be up (hopefully) tomorrow.

**Comment by SokyranTheDragon** [comment] 2021-11-09 23:13
And it seems like the original issue was due to FutureMC renaming `FireproofArmorItem` to `NetheriteArmorItem`. Just compiling with the most recent version of FutureMC should be enough, but seems like the FutureMC dev did some changes to fix stuff on their end. And this requires a little bit of tiny changes.

**Comment by SokyranTheDragon** [comment] 2021-11-16 00:46
I've uploaded the new update. It's currently "Under Review", so hopefully it'll be up soon.

**Closed as completed by SokyranTheDragon** 2021-11-16 00:46 UTC

**Comment by aking4125** [comment] 2021-11-16 13:30
Can confirm this is working! Wow, amazing job!
