### ISSUE TITLE
crash with new version (1.9c)

### ISSUE THREAD

**Issue by levmeister** [SokyranTheDragon/Minor-Integrations-and-Additions-MIA-#21] opened 2020-08-06 04:10 UTC
hey, I just installed 1.9c to a modpack I downloaded today ( https://www.curseforge.com/minecraft/modpacks/minecraft-eternal , however I also added crossroads and its dependency, essentials.) I am getting a crash on startup, apparently because the Thermal expansion/ Dungeon tactics integration is having issues with the iron club. The modpack does include both mentioned mods. The log has this to say:  

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Minor Integrations and Additions (mia)
Caused by: java.lang.NoSuchFieldError: IRON_CLUB
    at com.github.sokyranthedragon.mia.integrations.dungeontactics.ThermalExpansionDungeonTacticsIntegration.addRecipes(ThermalExpansionDungeonTacticsIntegration.java:30)
    at com.github.sokyranthedragon.mia.integrations.thermalexpansion.ThermalExpansion.init(ThermalExpansion.java:73)
    at com.github.sokyranthedragon.mia.integrations.base.ModIntegrator.init(ModIntegrator.java:194)
    at com.github.sokyranthedragon.mia.proxy.CommonProxy.init(CommonProxy.java:103)
    at com.github.sokyranthedragon.mia.proxy.ClientProxy.init(ClientProxy.java:41)
    at com.github.sokyranthedragon.mia.Mia.init(Mia.java:91)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
    at net.minecraft.client.Minecraft.init(Minecraft.java:535)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by levmeister** [comment] 2020-08-06 04:14
I turned off TE integration in the dungeon tactics config (in the mia folder), and am now trying to start the game again. So many mods, it may take a minute... 
Edit: That worked! So it's just a problem with the TE / DT integration module apparently. Now to enjoy :D

**Comment by SokyranTheDragon** [comment] 2020-08-06 22:22
Hmm... I think I see what the issue is. The modpack you're using must be using a little outdated version of Dungeon Tactics. The version 0.16.7 added new features, block, items, etc. which I'm accessing. Thankfully, you were able to disable the integration, which helped with the issue.

I'll look into automatically disabling the integrations that are cause issues, so this should make using my mod more convenient.

**Comment by SokyranTheDragon** [comment] 2020-08-07 10:48
Should be fixed by 1a43d5cfe0e5e665959b2ac48a46115a385aeeb9

**Closed as completed by SokyranTheDragon** 2020-08-07 10:48 UTC
