### ISSUE TITLE
Music player continues to play music if the item is moved to a container or anything else with a GUI

### ISSUE THREAD

**Issue by aking4125** [SokyranTheDragon/Minor-Integrations-and-Additions-MIA-#8] opened 2020-01-31 09:43 UTC
Best way to explain it, is to the insert a music disc into the music player. Then place the music player item into say, a chest. The music will keep playing. Worse yet, you can actually void the item by say, moving it to a trash bin. 

If you get a new music player to play a new track, it just plays both tracks simultaneously. The only way to stop it is to log out of the Single player world or server. There is no other way that I found to stop that. 

This could be a potential issue if, say there was a block or item that just takes the item out of a players inventory by accident somehow or if the player moves the music player to, say a trash bin by mistake.

**Comment by SokyranTheDragon** [comment] 2020-01-31 12:08
Hmm... That's strange. I was pretty sure I made sure it couldn't happen. Well, I guess I'll have to look into that then.

**Comment by SokyranTheDragon** [comment] 2020-01-31 14:33
Oh, I think I see where the issue is. When a rather serious bug I had to change the music player a bit, and seems like I forgot to include the part responsible for checking played songs without music player in the inventory. Should be fixed soon.

**Comment by aking4125** [comment] 2020-01-31 18:36
Copy that. No worries at all.

**Comment by SokyranTheDragon** [comment] 2020-01-31 18:39
It was slightly delayed due to a small issue that popped up after fixing this, but the fix should be up really soon.

**Closed as completed** 2020-01-31 18:40 UTC
Labels: bug

**Comment by aking4125** [comment] 2020-02-01 10:32
Yep this seemed to have completely fixed it. Thank you for the quick response!
